# Generated by Django 3.0.9 on 2020-08-26 15:03

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAPIQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=50, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('sources', models.CharField(blank=True, max_length=200, null=True)),
                ('query_type', models.CharField(choices=[('top-headlines', 'Top Headlines'), ('everything', 'Everything')], default='top-headlines', max_length=13)),
            ],
        ),
    ]
