# Generated by Django 3.0.9 on 2020-08-26 15:47

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsapiquery',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
