# Generated by Django 3.0.9 on 2020-08-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200826_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('publish_date', models.DateTimeField()),
            ],
        ),
    ]
