# Generated by Django 3.0.9 on 2020-08-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200826_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsapiquery',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('de', 'German'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('he', 'Hebrew'), ('it', 'Italian'), ('nl', 'Dutch'), ('no', 'Norwegian'), ('pt', 'Portuguese'), ('ru', 'Russia'), ('se', 'Swedish'), ('zh', 'Chinese')], default='en', max_length=2),
        ),
    ]
